
service: juanlescano-integrador-gift

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:us-east-1:450865910417:table/juanjoselescano-clients

functions:
  create-card:
    handler: create-gift.handler
    description: 'An API that create new gifts'
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:450865910417:juanjoselescano-createdCard
